name: decay2phasespace
channels:
  - default
dependencies:
  - python=3.9
  - pip
  - pip:
    - DecayLanguage
    - phasespace
    - particle
    - zfit
    - git+https://github.com/zfit/zfit-physics  # TODO change this to just zfit-physics once new release comes out
